# Generated by Django 5.0.7 on 2024-07-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_employee_check_in_remove_employee_check_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='logout_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
