# Generated by Django 5.0.7 on 2024-07-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_rename_employee_attendancerecord_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='login_work_location',
            field=models.CharField(blank=True, choices=[('Noida', 'Noida'), ('Gurugram', 'Gurugram'), ('Home', 'Home')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='logout_work_location',
            field=models.CharField(blank=True, choices=[('Noida', 'Noida'), ('Gurugram', 'Gurugram'), ('Home', 'Home')], max_length=50, null=True),
        ),
    ]
