# Generated by Django 5.0.7 on 2024-07-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendancerecord_login_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeworkingdetails',
            old_name='is_present',
            new_name='is_present_first_half',
        ),
        migrations.AddField(
            model_name='employeeworkingdetails',
            name='is_present_second_half',
            field=models.BooleanField(default=False),
        ),
    ]
