# Generated by Django 5.0.7 on 2024-07-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_employeeworkingdetails_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeworkingdetails',
            name='location',
        ),
    ]
